language: node_js
node_js:
  - "10"
notifications:
  email: false
before_install:
# package-lock.json was introduced in npm@5
  - '[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest' # skipped when using node 9
script:
  - npm test && npm run integration
